### ISSUE TITLE
Funktion #4 kann nicht aufgerufen werden

### ISSUE THREAD

**Issue by NilsRueffer** [NilsRueffer/Wissenschaftliches_Arbeiten_Leistung3#12]
Intern in der Funktion werden x und y verwendet, während in der shell-function "metricVariables" und "dichotomousVariables" verwendet werden. Nirgendwo wird eine Übersetzung dieser Variablennamen o.ä. durchgeführt und die inneren Funktionen werden nicht aufgerufen.

**Comment by kaba19-web** [comment]
Ich hane jetzt die Variablen angesspt. Die Funktion kann jetzt aufgerufen werden.

**Comment by NilsRueffer** [comment]
Sehr gut, jetzt sollte sie aufrufbar sein. Du kannst theoretisch noch die sd.pop - Funktion in die Helferfunktionen schreiben.

**Comment by NilsRueffer** [comment]
Ok, hab ich jetzt einfach gemacht.

**Comment by kaba19-web** [comment]
Alles klar, ich habe gesehen.
Dankeschön
