### ISSUE TITLE
Metrische Variablen

### ISSUE THREAD

**Issue by MattiasKeppke** [NilsRueffer/Wissenschaftliches_Arbeiten_Leistung3#2]
Würdet ihr das Interesse an Mathe und Porgrammieren als metrische Variable auffassen?

**Comment by Tatascie** [comment]
Mathe und Programmieren sind ordinale Variablen, aber theoretisch können wir sie als metrische Variablen auffassen - denke ich.

**Comment by UweTUDO** [comment]
Dem würde ich auch zustimmen. Genau genommen eine Ordinate Variable. Wird aber so behandelt wie eine metrische Variable.
