### ISSUE TITLE
Assigning Aufgabe 4 

### ISSUE THREAD

**Issue by Tatascie** [NilsRueffer/Wissenschaftliches_Arbeiten_Leistung3#20]
Hallo zusammen, 
was sollen wir für Aufgabe 4 machen ? Wie teilen wir die Augabe ? @kaba19-web @UweTUDO

**Comment by UweTUDO** [comment]
script4 initial erstellt.
Die 7 Funktionen aus script2 sind in der Analyse mindestens zu verwenden. Ansonsten alles was R zu bieten hat.
Jeder sucht sich eine beliebige Funktion aus (im Projektplan oder besser hier kurz bekannt geben, damit wir möglichst schnell alle Funktionen einmal benutzt haben.) macht die Analyse und schreibt diese mit Beschreibung und Ergebnis in script4, damit die anderen die vermeintlichen Ergebnisse sehen. Die Zeit für eine solche Änderung sollte recht kurz (Stunde) sein! Dann können wir auch darüber Diskutieren.  Bei auftretenden Fehlern Funktion korrigieren oder wenn zu kompliziert Issue erstellen.

**Comment by UweTUDO** [comment]
Offene Punkte am Mittwoch Abend besprechen und verteilen.

**Comment by UweTUDO** [comment]
Übernahme der bisherigen Analyse und Analyse mit Funktion 6 - beginn

**Comment by UweTUDO** [comment]
Übernahme erfolgt

**Comment by UweTUDO** [comment]
füge Aufruf Funktion 2 und 3 hinzu

**Comment by UweTUDO** [comment]
Aufrufe hizugefuehgt
vorhanden (2,3,6) uebernommen(1,4) offen (5)

**Comment by UweTUDO** [comment]
Alle Aufgaben verteilt und bearbeitet.
