### ISSUE TITLE
uebergabe des Repositories 27.2.2021

### ISSUE THREAD

**Issue by UweTUDO** [NilsRueffer/Wissenschaftliches_Arbeiten_Leistung3#22]
Wärest du bereit die Übergabe des Repositories an die Dozentin zu machen und danach diesen Issue zu schließen?

**Comment by NilsRueffer** [comment]
INwiefern die Übergabe? Muss ich nicht einfach nur den Link da angeben?

**Comment by NilsRueffer** [comment]
Bzw. müssen wir nicht alle einfach den Link zu diesem Repository da angeben?

**Comment by UweTUDO** [comment]
Hast recht, das war mir neu!
 GitHub-Repository-Link
Bitte geben Sie hier (jedes Gruppenmitglied einzeln bitte) den Link zum GitHub-Repository Ihrer Gruppe ein. Bitte stellen Sie sicher, dass dieses für mich sichtbar ist.
Wobei mir
Bitte stellen Sie sicher, dass dieses für mich sichtbar ist.
Fragen aufwirft!

**Comment by UweTUDO** [comment]
Du hattest uns doch zugriff erteilt.
Nun müsstest du doch ihr auch Zugriff geben, sonst nutzt der Link doch nichts?! Oder?

**Comment by NilsRueffer** [comment]
Der Zugriff bezog sich darauf Änderungen an dem Repository vorzunehmen, nicht darauf das anzusehen; das Repository ist öffentlich sichtbar.

**Comment by UweTUDO** [comment]
Ok, dann mach ich den Issue zu!
