### ISSUE TITLE
Assign Aufgabe - Skript 1

### ISSUE THREAD

**Issue by Tatascie** [NilsRueffer/Wissenschaftliches_Arbeiten_Leistung3#8]
- Mattias hat Funktionen a & b gemacht
- Kaba: d
- Ich (Thao) nehme dann Funktion c. 
Wir haben noch e und f, die Uwe & Nils nehmen sollen. 
Bitte schreiben in die Kommentar, welche Aufgabe ihr arbeiten möchtet.

**Comment by NilsRueffer** [comment]
Ich übernehme dann e, da ich Visualisierung nicht so gut kann.

**Comment by UweTUDO** [comment]
Ich hatte nur das script2 genommen. Da kamen leider keine Anforderungen.
f wird problematisch! und ist somit noch offen!

**Comment by UweTUDO** [comment]
Habe begonnen eine rudimentäre Funktion für f zu erstellen.

**Comment by UweTUDO** [comment]
Funktion rudimentär erstellt.
